plugins:
  - remark-heading-id
  - remark-validate-links
  - remark-frontmatter
  - - remark-lint-frontmatter-schema
    - schemas:
        ./.github/linters/metadata.schema.yml:
          - ./src/pages/**/*.md
