properties:
  title:
    type: string
    maxLength: 60
  description:
    type: string
    maxLength: 160
  keywords:
    type: array
    items:
      type: string
      enum:
        - API Mesh
        - App Builder
        - B2B
        - Backend Development
        - Cache
        - Checkout
        - Cloud
        - Configuration
        - Cron
        - Events
        - Extensibility
        - Extensions
        - GraphQL
        - Integration
        - Install
        - Inventory
        - Logs
        - Native Luma Frontend Development
        - Page Builder
        - Payments
        - Performance
        - REST
        - Security
        - Storefront
        - Themes
        - Tools
        - Upgrade

required:
  - title
  - description