##### Aggregate Commerce PRs and Issues into a respective Organizational Project #####

name: Add pull requests and issues to projects

on:
  pull_request_target:
    types:
      - opened
  issues:
    types: 
      - opened

jobs:
  call-workflow-add-to-project:
    uses: AdobeDocs/commerce-php/.github/workflows/add-to-project_job.yml@main
    secrets: inherit
