---
name: PR Comment
on:
  workflow_run:
    workflows: ["PR validation"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/pr-comment-v3.yml@main
    with:
      run_id: ${{ github.event.workflow_run.id }}
      event: ${{ github.event.workflow_run.event }}
